"""
Handles asynchronous gRPC streaming to the action-service.
"""
import grpc
import queue
import threading
import time
import sys
import os

# Dynamically add the 'pb' directory to Python's path so the autogenerated 
# files can find each other without throwing a ModuleNotFoundError.
pb_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'pb'))
sys.path.append(pb_dir)

import tracker_pb2
import tracker_pb2_grpc

class GazeStreamer:
    def __init__(self, target_address='localhost:50051'):
        self.target = target_address
        self.channel = grpc.insecure_channel(self.target)
        self.stub = tracker_pb2_grpc.EyeTrackerStub(self.channel)
        
        # Maxsize prevents memory leaks if the server is offline
        self.queue = queue.Queue(maxsize=60) 
        self.is_streaming = False
        self._thread = None

    def start(self):
        """Starts the background streaming thread."""
        self.is_streaming = True
        self._thread = threading.Thread(target=self._stream_loop, daemon=True)
        self._thread.start()
        print(f"gRPC Streamer started, targeting {self.target}")

    def stop(self):
        """Cleanly shuts down the stream."""
        self.is_streaming = False
        if self._thread:
            self._thread.join(timeout=1.0)
        self.channel.close()
        print("gRPC Streamer shut down.")

    def send_point(self, x, y, confidence):
        """Pushes a coordinate to the queue to be sent to Go."""
        if not self.is_streaming:
            return
        try:
            # nanosecond integer math to avoid float rounding errors
            timestamp_ms = time.time_ns() // 1_000_000
            
            self.queue.put_nowait((x, y, confidence, timestamp_ms))
        except queue.Full:
            pass

    def _generate_messages(self):
        """Yields messages from the queue to the gRPC stream."""
        while self.is_streaming:
            try:
                # Timeout allows the loop to periodically check if is_streaming is False
                x, y, conf, ts = self.queue.get(timeout=0.1)
                yield tracker_pb2.GazePoint(x=x, y=y, confidence=conf, timestamp=ts)
            except queue.Empty:
                continue

    def _stream_loop(self):
        """The core loop running in the background thread."""
        try:
            # This line blocks and continuously sends data from _generate_messages
            response = self.stub.StreamCoordinates(self._generate_messages())
            print(f"Server closed stream with message: {response.message}")
        except grpc.RpcError as e:
            print(f"gRPC connection dropped: {e.code().name}")